/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9ceaaf51-4023-4800-8d11-0d89c259e776",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zbX54are6",
    "aws_user_pools_web_client_id": "3n8t7kkdot2qcqq3cfeivijcse",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://h4lflpt5arehho6o47eriycre4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
